version: '3'
services:
  java-otel-log:
    build: java-otel-log/
    ports:
      - 8090:8090
    volumes:
      - ./logs:/logs
    env_file: ".env"
    depends_on:
      - filebeat

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.2
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/elastic.log:/logs/elastic.log
    env_file: ".env"